name: dart_node_example
description: A sample command-line application.
version: 0.0.0
repository: https://github.com/iapicca/dart_node_example

environment:
  sdk: ^3.4.0

dependencies:
  js: ^0.7.1

dev_dependencies:
  lints: ^3.0.0
